spring.application.name=shopflow
spring.datasource.url=jdbc:mysql://localhost:3306/shopflow?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jawad@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jawadkhan26661@gmail.com
spring.mail.password=xigycqulepbpimmw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true